/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ApplicationGui;
import SubFrames.AddEquipmentFrame;
import java.util.ArrayList;
import Classes.Equipment;
import java.awt.Color;
import javax.swing.DefaultListModel;


/**
 *
 * @author Dell 2024
 */
public class EquipmentFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EquipmentFrame.class.getName());
    public static ArrayList<Equipment> equipmentsList = new ArrayList();

    /**
     * Creates new form EquipmentFrame
     */
    public EquipmentFrame() {
        initComponents();
        this.setDefaultCloseOperation(EquipmentFrame.DISPOSE_ON_CLOSE);
         this.getContentPane().setBackground(new Color(18, 17, 17));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddEquipmentButton = new javax.swing.JButton();
        RemoveEquipmentButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        EquipmentsList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddEquipmentButton.setBackground(new java.awt.Color(0, 0, 0));
        AddEquipmentButton.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        AddEquipmentButton.setForeground(new java.awt.Color(255, 255, 255));
        AddEquipmentButton.setText("Add New Equipment");
        AddEquipmentButton.addActionListener(this::AddEquipmentButtonActionPerformed);

        RemoveEquipmentButton.setBackground(new java.awt.Color(0, 0, 0));
        RemoveEquipmentButton.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        RemoveEquipmentButton.setForeground(new java.awt.Color(255, 255, 255));
        RemoveEquipmentButton.setText("Remove Equipment");
        RemoveEquipmentButton.addActionListener(this::RemoveEquipmentButtonActionPerformed);

        jScrollPane2.setViewportView(EquipmentsList);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell 2024\\Desktop\\miniProject_EventRegSys\\src\\main\\java\\ApplicationGui\\tool(1).png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddEquipmentButton)
                            .addComponent(RemoveEquipmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(131, 131, 131)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(AddEquipmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(RemoveEquipmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddEquipmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEquipmentButtonActionPerformed
AddEquipmentFrame addFrame = new AddEquipmentFrame();
addFrame.setVisible(true);
    }//GEN-LAST:event_AddEquipmentButtonActionPerformed

    private void RemoveEquipmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveEquipmentButtonActionPerformed
        int selectedIndex = EquipmentFrame.EquipmentsList.getSelectedIndex();
        if (selectedIndex == -1) return;
        Equipment e = EquipmentFrame.equipmentsList.get(selectedIndex);
        EquipmentFrame.deleteEquipment(e);
EquipmentFrame.loadEquipmentToList();
    }//GEN-LAST:event_RemoveEquipmentButtonActionPerformed

   public static void loadEquipmentToList(){
       DefaultListModel<String> model = new DefaultListModel<>(); 
       
       for (Equipment eq : EquipmentFrame.equipmentsList){
           String display =eq.id +  " " + eq.name + " Quantity : " + eq.quantityAvailable;
           model.addElement(display);
       }
       EquipmentFrame.EquipmentsList.setModel(model);
   }
   
   
   public static void deleteEquipment(Equipment e){
       EquipmentFrame.equipmentsList.remove(e);
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEquipmentButton;
    private static javax.swing.JList<String> EquipmentsList;
    private javax.swing.JButton RemoveEquipmentButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
