/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ApplicationGui;
import SubFrames.AddEventFrame;
import java.util.ArrayList;
import Classes.Event;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import Classes.Student;

/**
 *
 * @author Dell 2024
 */
public class EventFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EventFrame.class.getName());
    public static ArrayList<Event>eventsList= new ArrayList();

    /**
     * Creates new form EventFrame
     */
    public EventFrame() {
        initComponents();
         this.getContentPane().setBackground(new Color(18, 17, 17));
        this.setDefaultCloseOperation(EventFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddEventButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        EventTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        CancelEventButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddEventButton.setBackground(new java.awt.Color(0, 0, 0));
        AddEventButton.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        AddEventButton.setForeground(new java.awt.Color(255, 255, 255));
        AddEventButton.setText("Schedule New Event");
        AddEventButton.addActionListener(this::AddEventButtonActionPerformed);

        EventTable.setBackground(new java.awt.Color(0, 0, 0));
        EventTable.setForeground(new java.awt.Color(255, 255, 255));
        EventTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Code", "Title", "Date", "Start Hour", "End Hour", "Max Participants"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(EventTable);
        if (EventTable.getColumnModel().getColumnCount() > 0) {
            EventTable.getColumnModel().getColumn(0).setResizable(false);
            EventTable.getColumnModel().getColumn(1).setResizable(false);
            EventTable.getColumnModel().getColumn(2).setResizable(false);
            EventTable.getColumnModel().getColumn(3).setResizable(false);
            EventTable.getColumnModel().getColumn(4).setResizable(false);
            EventTable.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell 2024\\Desktop\\miniProject_EventRegSys\\src\\main\\java\\ApplicationGui\\calendar.png")); // NOI18N

        CancelEventButton.setBackground(new java.awt.Color(0, 0, 0));
        CancelEventButton.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        CancelEventButton.setForeground(new java.awt.Color(255, 255, 255));
        CancelEventButton.setText("Cancel Event");
        CancelEventButton.addActionListener(this::CancelEventButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AddEventButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CancelEventButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddEventButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(CancelEventButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEventButtonActionPerformed
AddEventFrame addFrame = new AddEventFrame();
addFrame.setVisible(true);
    }//GEN-LAST:event_AddEventButtonActionPerformed

    private void CancelEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelEventButtonActionPerformed
    int selectedIndex = EventFrame.EventTable.getSelectedRow();
    if (selectedIndex == -1) return;
    
 Event e =  EventFrame.eventsList.get(selectedIndex);
 EventFrame.removeEvent(e);
 EventFrame.loadEventsToTable();
     
    }//GEN-LAST:event_CancelEventButtonActionPerformed

public static void loadEventsToTable(){
    DefaultTableModel model = (DefaultTableModel) EventTable.getModel();
    model.setRowCount(0);
    
    for(Event evt : EventFrame.eventsList){
        Object[ ] row = {
        evt.code,evt.title,evt.date,evt.startHour,evt.endHour,evt.maxParticipants
        };
        model.addRow(row);
    }
    
}

public static void removeEvent(Event e){
    EventFrame.eventsList.remove(e);
    
    for (Student s : e.students){
        s.registeredEvents.remove(e);
    }
    e.organizer.managedEvents.remove(e);
}
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEventButton;
    private javax.swing.JButton CancelEventButton;
    private static javax.swing.JTable EventTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
