/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ApplicationGui;
import SubFrames.*;
import javax.swing.JPanel;
import java.awt.Color;


/**
 *
 * @author Dell 2024
 */
public class MainMenuFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenuFrame.class.getName());

    /**
     * Creates new form MainMenuFrame
     */
    public MainMenuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        ManageStudentsButton = new javax.swing.JButton();
        ManageOrganizersButton = new javax.swing.JButton();
        ManageRoomsButton = new javax.swing.JButton();
        ManageEquipmentButton = new javax.swing.JButton();
        ManageEventsButton = new javax.swing.JButton();
        RegisterToEventButton = new javax.swing.JButton();
        ReportsButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        Title.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(253, 111, 0));
        Title.setText("Campus Event Registration System");

        ManageStudentsButton.setBackground(new java.awt.Color(0, 0, 0));
        ManageStudentsButton.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        ManageStudentsButton.setForeground(new java.awt.Color(255, 255, 255));
        ManageStudentsButton.setText("Manage Students");
        ManageStudentsButton.setBorderPainted(false);
        ManageStudentsButton.addActionListener(this::ManageStudentsButtonActionPerformed);

        ManageOrganizersButton.setBackground(new java.awt.Color(0, 0, 0));
        ManageOrganizersButton.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        ManageOrganizersButton.setForeground(new java.awt.Color(255, 255, 255));
        ManageOrganizersButton.setText("Manage Organizers");
        ManageOrganizersButton.setBorderPainted(false);
        ManageOrganizersButton.addActionListener(this::ManageOrganizersButtonActionPerformed);

        ManageRoomsButton.setBackground(new java.awt.Color(0, 0, 0));
        ManageRoomsButton.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        ManageRoomsButton.setForeground(new java.awt.Color(255, 255, 255));
        ManageRoomsButton.setText("Manage Rooms");
        ManageRoomsButton.setBorderPainted(false);
        ManageRoomsButton.addActionListener(this::ManageRoomsButtonActionPerformed);

        ManageEquipmentButton.setBackground(new java.awt.Color(0, 0, 0));
        ManageEquipmentButton.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        ManageEquipmentButton.setForeground(new java.awt.Color(255, 255, 255));
        ManageEquipmentButton.setText("Manage Equipment");
        ManageEquipmentButton.setBorderPainted(false);
        ManageEquipmentButton.addActionListener(this::ManageEquipmentButtonActionPerformed);

        ManageEventsButton.setBackground(new java.awt.Color(0, 0, 0));
        ManageEventsButton.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        ManageEventsButton.setForeground(new java.awt.Color(255, 255, 255));
        ManageEventsButton.setText("Manage Events");
        ManageEventsButton.setBorderPainted(false);
        ManageEventsButton.addActionListener(this::ManageEventsButtonActionPerformed);

        RegisterToEventButton.setBackground(new java.awt.Color(0, 0, 0));
        RegisterToEventButton.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        RegisterToEventButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterToEventButton.setText("Register For Event");
        RegisterToEventButton.setBorderPainted(false);
        RegisterToEventButton.addActionListener(this::RegisterToEventButtonActionPerformed);

        ReportsButton.setBackground(new java.awt.Color(0, 0, 0));
        ReportsButton.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        ReportsButton.setForeground(new java.awt.Color(255, 255, 255));
        ReportsButton.setText("View Reports");
        ReportsButton.setBorderPainted(false);
        ReportsButton.addActionListener(this::ReportsButtonActionPerformed);

        ExitButton.setBackground(new java.awt.Color(0, 0, 0));
        ExitButton.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("Exit");
        ExitButton.setBorderPainted(false);
        ExitButton.addActionListener(this::ExitButtonActionPerformed);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell 2024\\Desktop\\miniProject_EventRegSys\\src\\main\\java\\ApplicationGui\\calendar(1).png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ReportsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ManageEquipmentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ManageStudentsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ManageOrganizersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ManageEventsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ManageRoomsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegisterToEventButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManageStudentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageOrganizersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageRoomsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManageEquipmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageEventsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterToEventButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReportsButton)
                    .addComponent(ExitButton))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManageEventsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEventsButtonActionPerformed

        
        EventFrame eventFrame = new EventFrame();
        eventFrame.setVisible(true);
        EventFrame.loadEventsToTable();
    }//GEN-LAST:event_ManageEventsButtonActionPerformed

    private void ManageStudentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageStudentsButtonActionPerformed
      
        StudentFrame studentFrame = new StudentFrame();
       studentFrame.setVisible(true); 
       StudentFrame.loadStudentsToTable();
       
    }//GEN-LAST:event_ManageStudentsButtonActionPerformed

    private void ManageOrganizersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageOrganizersButtonActionPerformed

        OrganizerFrame organizerFrame = new OrganizerFrame();
      organizerFrame.setVisible(true);
      OrganizerFrame.loadOrganizersToTable();
    }//GEN-LAST:event_ManageOrganizersButtonActionPerformed

    private void ManageEquipmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEquipmentButtonActionPerformed
EquipmentFrame equipmentFrame = new EquipmentFrame();
equipmentFrame.setVisible(true);
EquipmentFrame.loadEquipmentToList();

    }//GEN-LAST:event_ManageEquipmentButtonActionPerformed

    private void ManageRoomsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageRoomsButtonActionPerformed

        RoomFrame roomFrame = new RoomFrame();
  roomFrame.setVisible(true);
  RoomFrame.loadRoomsToTable();
    }//GEN-LAST:event_ManageRoomsButtonActionPerformed

    private void RegisterToEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterToEventButtonActionPerformed
RegistrationFrame registrationFrame = new RegistrationFrame();
registrationFrame.setVisible(true);

    }//GEN-LAST:event_RegisterToEventButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ReportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportsButtonActionPerformed
        ReportFrame reportFrame = new ReportFrame();
        reportFrame.setVisible(true);;
        ReportFrame.loadRegistraionsToTable();
    }//GEN-LAST:event_ReportsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[ ] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      MainMenuFrame mainMenu =  new MainMenuFrame();
     
      mainMenu.getContentPane().setBackground(new Color(18, 17, 17));
      mainMenu.setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton ManageEquipmentButton;
    private javax.swing.JButton ManageEventsButton;
    private javax.swing.JButton ManageOrganizersButton;
    private javax.swing.JButton ManageRoomsButton;
    private javax.swing.JButton ManageStudentsButton;
    private javax.swing.JButton RegisterToEventButton;
    private javax.swing.JButton ReportsButton;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
