/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ApplicationGui;
import SubFrames.AddOrganizerFrame;
import java.util.ArrayList;
import Classes.Organizer;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Dell 2024
 */
public class OrganizerFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OrganizerFrame.class.getName());
    public static ArrayList<Organizer> organizersList = new ArrayList();

    /**
     * Creates new form OrganizerFrame
     */
    public OrganizerFrame() {
        initComponents();
        this.setDefaultCloseOperation(OrganizerFrame.DISPOSE_ON_CLOSE);
         this.getContentPane().setBackground(new Color(18, 17, 17));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddOrganizerButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrganizersTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddOrganizerButton.setBackground(new java.awt.Color(0, 0, 0));
        AddOrganizerButton.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        AddOrganizerButton.setForeground(new java.awt.Color(255, 255, 255));
        AddOrganizerButton.setText("Add New Organizer");
        AddOrganizerButton.addActionListener(this::AddOrganizerButtonActionPerformed);

        OrganizersTable.setBackground(new java.awt.Color(0, 0, 0));
        OrganizersTable.setForeground(new java.awt.Color(255, 255, 255));
        OrganizersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Email", "Club Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(OrganizersTable);
        if (OrganizersTable.getColumnModel().getColumnCount() > 0) {
            OrganizersTable.getColumnModel().getColumn(0).setResizable(false);
            OrganizersTable.getColumnModel().getColumn(1).setResizable(false);
            OrganizersTable.getColumnModel().getColumn(2).setResizable(false);
            OrganizersTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell 2024\\Desktop\\miniProject_EventRegSys\\src\\main\\java\\ApplicationGui\\user.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddOrganizerButton)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addGap(59, 59, 59)
                        .addComponent(AddOrganizerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddOrganizerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddOrganizerButtonActionPerformed
AddOrganizerFrame addFrame = new AddOrganizerFrame();
addFrame.setVisible(true);
    }//GEN-LAST:event_AddOrganizerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void loadOrganizersToTable(){
        DefaultTableModel model = (DefaultTableModel) OrganizersTable.getModel();
        model.setRowCount(0);
        
        for (Organizer org : organizersList){
            Object[] row = {
              org.id
             ,org.name
             ,org.email
             ,org.clubName
            };
            model.addRow(row);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddOrganizerButton;
    private static javax.swing.JTable OrganizersTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
