/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ApplicationGui;
import Classes.Registration;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell 2024
 */
public class ReportFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportFrame.class.getName()); 
    public static ArrayList<Registration> registrationsList = new ArrayList<>();

    /**
     * Creates new form ReportFrame
     */
    public ReportFrame() {
        initComponents();
         this.getContentPane().setBackground(new Color(18, 17, 17));
           this.setDefaultCloseOperation(StudentFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        RegistrationsTable = new javax.swing.JTable();
        CancelRegistrationButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RegistrationsTable.setBackground(new java.awt.Color(0, 0, 0));
        RegistrationsTable.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Reg ID", "Reg Date", "Student ID", "Student Name", "Status", "Event Code", "Event Title"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(RegistrationsTable);
        if (RegistrationsTable.getColumnModel().getColumnCount() > 0) {
            RegistrationsTable.getColumnModel().getColumn(0).setResizable(false);
            RegistrationsTable.getColumnModel().getColumn(1).setResizable(false);
            RegistrationsTable.getColumnModel().getColumn(2).setResizable(false);
            RegistrationsTable.getColumnModel().getColumn(3).setResizable(false);
            RegistrationsTable.getColumnModel().getColumn(4).setResizable(false);
            RegistrationsTable.getColumnModel().getColumn(5).setResizable(false);
            RegistrationsTable.getColumnModel().getColumn(6).setResizable(false);
        }

        CancelRegistrationButton.setBackground(new java.awt.Color(0, 0, 0));
        CancelRegistrationButton.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        CancelRegistrationButton.setForeground(new java.awt.Color(255, 255, 255));
        CancelRegistrationButton.setText("Cancel Registration");
        CancelRegistrationButton.addActionListener(this::CancelRegistrationButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(CancelRegistrationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(CancelRegistrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelRegistrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelRegistrationButtonActionPerformed
     int selectedIndex = ReportFrame.RegistrationsTable.getSelectedRow();
     if (selectedIndex == -1) return;
     
     Registration r = ReportFrame.registrationsList.get(selectedIndex);
     r.cancelRegistration();
       ReportFrame.loadRegistraionsToTable();
    }//GEN-LAST:event_CancelRegistrationButtonActionPerformed

   public static void loadRegistraionsToTable(){
       DefaultTableModel model = (DefaultTableModel) RegistrationsTable.getModel();
       model.setRowCount(0);
      
       for (Registration reg : ReportFrame.registrationsList){
           Object[ ] row = {
             reg.registrationId , reg.registrationDate,reg.student.id,reg.student.name,reg.status,reg.event.code,reg.event.title
           };
           
          model.addRow(row);
       }
      
   }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelRegistrationButton;
    private static javax.swing.JTable RegistrationsTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
