/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ApplicationGui;
import SubFrames.AddRoomFrame;
import java.util.ArrayList;
import Classes.Room;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell 2024
 */
public class RoomFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RoomFrame.class.getName());
    public static ArrayList<Room> roomsList = new ArrayList();

    /**
     * Creates new form RoomFrame
     */
    public RoomFrame() {
        initComponents();
        this.setDefaultCloseOperation(RoomFrame.DISPOSE_ON_CLOSE);
         this.getContentPane().setBackground(new Color(18, 17, 17));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddRoomButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        RoomsTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddRoomButton.setBackground(new java.awt.Color(0, 0, 0));
        AddRoomButton.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        AddRoomButton.setForeground(new java.awt.Color(255, 255, 255));
        AddRoomButton.setText("Add New Room");
        AddRoomButton.addActionListener(this::AddRoomButtonActionPerformed);

        RoomsTable.setBackground(new java.awt.Color(0, 0, 0));
        RoomsTable.setForeground(new java.awt.Color(255, 255, 255));
        RoomsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Room Number", "Building", "Capacity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(RoomsTable);
        if (RoomsTable.getColumnModel().getColumnCount() > 0) {
            RoomsTable.getColumnModel().getColumn(0).setResizable(false);
            RoomsTable.getColumnModel().getColumn(1).setResizable(false);
            RoomsTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell 2024\\Desktop\\miniProject_EventRegSys\\src\\main\\java\\ApplicationGui\\school.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AddRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGap(59, 59, 59)
                        .addComponent(AddRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRoomButtonActionPerformed
AddRoomFrame addFrame = new AddRoomFrame();
addFrame.setVisible(true);
    }//GEN-LAST:event_AddRoomButtonActionPerformed

    public static void loadRoomsToTable(){
     DefaultTableModel model = (DefaultTableModel) RoomsTable.getModel();
        model.setRowCount(0);
        
        for (Room room : RoomFrame.roomsList){
            Object[ ] row = {
                room.roomNumber,room.building,room.capacity
            } ;
            model.addRow(row);
        }
    
}



   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRoomButton;
    private static javax.swing.JTable RoomsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
