/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ApplicationGui;
import SubFrames.AddStudentFrame;
import Classes.Student;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import  Classes.Event;
/**
 *
 * @author Dell 2024
 */
public class StudentFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentFrame.class.getName());
    
    public static ArrayList<Student> studentsList = new ArrayList();

    /**
     * Creates new form StudentFrame
     */
    public StudentFrame() {
        initComponents();
        this.getContentPane().setBackground(new Color(18, 17, 17));
    
        this.setDefaultCloseOperation(StudentFrame.DISPOSE_ON_CLOSE);
       
          
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddStudentButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentsTable = new javax.swing.JTable();
        RemoveStudentButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddStudentButton.setBackground(new java.awt.Color(0, 0, 0));
        AddStudentButton.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        AddStudentButton.setForeground(new java.awt.Color(255, 255, 255));
        AddStudentButton.setText("Add New Student");
        AddStudentButton.setBorderPainted(false);
        AddStudentButton.addActionListener(this::AddStudentButtonActionPerformed);

        StudentsTable.setBackground(new java.awt.Color(0, 0, 0));
        StudentsTable.setForeground(new java.awt.Color(255, 255, 255));
        StudentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Email", "Level", "Department"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StudentsTable.setToolTipText("");
        StudentsTable.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(StudentsTable);
        if (StudentsTable.getColumnModel().getColumnCount() > 0) {
            StudentsTable.getColumnModel().getColumn(0).setResizable(false);
            StudentsTable.getColumnModel().getColumn(1).setResizable(false);
            StudentsTable.getColumnModel().getColumn(2).setResizable(false);
            StudentsTable.getColumnModel().getColumn(3).setResizable(false);
            StudentsTable.getColumnModel().getColumn(4).setResizable(false);
        }

        RemoveStudentButton.setBackground(new java.awt.Color(0, 0, 0));
        RemoveStudentButton.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        RemoveStudentButton.setForeground(new java.awt.Color(255, 255, 255));
        RemoveStudentButton.setText("Remove Student");
        RemoveStudentButton.setBorderPainted(false);
        RemoveStudentButton.addActionListener(this::RemoveStudentButtonActionPerformed);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell 2024\\Desktop\\miniProject_EventRegSys\\src\\main\\java\\ApplicationGui\\student(4).png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RemoveStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddStudentButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(AddStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(RemoveStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentButtonActionPerformed
AddStudentFrame addFrame = new AddStudentFrame();
addFrame.setVisible(true);
    }//GEN-LAST:event_AddStudentButtonActionPerformed

    private void RemoveStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveStudentButtonActionPerformed
       int selectedIndex = StudentFrame.StudentsTable.getSelectedRow();
       if (selectedIndex == -1) return;
       Student s = StudentFrame.studentsList.get(selectedIndex);
       StudentFrame.removeStudent(s);
       StudentFrame.loadStudentsToTable();
    }//GEN-LAST:event_RemoveStudentButtonActionPerformed

  
   public static void loadStudentsToTable(){
       DefaultTableModel model =  (DefaultTableModel) StudentsTable.getModel();
       model.setRowCount(0);
       for (Student student : studentsList){
           Object[] row = {
             student.id,student.name,student.email,student.level,student.department
           };
           model.addRow(row);
       }
       
   }
   
   public static void removeStudent(Student s){
     StudentFrame.studentsList.remove(s);
    for (Event e : s.registeredEvents){
        e.students.remove(s);
    }
   }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddStudentButton;
    private javax.swing.JButton RemoveStudentButton;
    private static javax.swing.JTable StudentsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
