/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SubFrames;
import javax.swing.text.MaskFormatter;
import Classes.Event;
import javax.swing.JFormattedTextField;
import Classes.Room;
import Classes.Organizer;
import ApplicationGui.RoomFrame;
import ApplicationGui.OrganizerFrame;
import ApplicationGui.EventFrame;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import java.time.DateTimeException;
public class AddEventFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddEventFrame.class.getName());

    /**
     * Creates new form AddEventFrame
     */
    public AddEventFrame() {
        initComponents();
        this.setDefaultCloseOperation(AddEventFrame.DISPOSE_ON_CLOSE);
    
        
        
        for (Room room : RoomFrame.roomsList){
            SelectRoomCombo.addItem( room.roomNumber+ " " + room.building + " c : " + room.capacity);
        }
        for(Organizer org : OrganizerFrame.organizersList){
           organizerCombo.addItem(org.id + " " + org.name);
        }
        
         this.getContentPane().setBackground(new Color(18, 17, 17));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EventCodeTitle = new javax.swing.JLabel();
        EventDateTitle = new javax.swing.JLabel();
        EventNameTitle = new javax.swing.JLabel();
        StartHourTitle = new javax.swing.JLabel();
        EndingHourTitle = new javax.swing.JLabel();
        MaxParticipantsTitle = new javax.swing.JLabel();
        SelectRoomTitle = new javax.swing.JLabel();
        EventCodeField = new javax.swing.JTextField();
        EventNameField = new javax.swing.JTextField();
        StartingHourField = new javax.swing.JTextField();
        EventDateField = new javax.swing.JFormattedTextField();
        EndingHourField = new javax.swing.JTextField();
        MaxParticipantsSpinner = new javax.swing.JSpinner();
        SelectRoomCombo = new javax.swing.JComboBox<>();
        ScheduleEventButton = new javax.swing.JButton();
        organizerTitle = new javax.swing.JLabel();
        organizerCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EventCodeTitle.setBackground(new java.awt.Color(0, 0, 0));
        EventCodeTitle.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 12)); // NOI18N
        EventCodeTitle.setForeground(new java.awt.Color(255, 255, 255));
        EventCodeTitle.setText("Event Code");

        EventDateTitle.setBackground(new java.awt.Color(0, 0, 0));
        EventDateTitle.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 12)); // NOI18N
        EventDateTitle.setForeground(new java.awt.Color(255, 255, 255));
        EventDateTitle.setText("Event Date");

        EventNameTitle.setBackground(new java.awt.Color(0, 0, 0));
        EventNameTitle.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 12)); // NOI18N
        EventNameTitle.setForeground(new java.awt.Color(255, 255, 255));
        EventNameTitle.setText("EventTitle");

        StartHourTitle.setBackground(new java.awt.Color(0, 0, 0));
        StartHourTitle.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 12)); // NOI18N
        StartHourTitle.setForeground(new java.awt.Color(255, 255, 255));
        StartHourTitle.setText("Starting Hour");

        EndingHourTitle.setBackground(new java.awt.Color(0, 0, 0));
        EndingHourTitle.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 12)); // NOI18N
        EndingHourTitle.setForeground(new java.awt.Color(255, 255, 255));
        EndingHourTitle.setText("Ending Hour");

        MaxParticipantsTitle.setBackground(new java.awt.Color(0, 0, 0));
        MaxParticipantsTitle.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 12)); // NOI18N
        MaxParticipantsTitle.setForeground(new java.awt.Color(255, 255, 255));
        MaxParticipantsTitle.setText("Max Participants");

        SelectRoomTitle.setBackground(new java.awt.Color(0, 0, 0));
        SelectRoomTitle.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 12)); // NOI18N
        SelectRoomTitle.setForeground(new java.awt.Color(255, 255, 255));
        SelectRoomTitle.setText("Select Room");

        try {
            EventDateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        EventDateField.addActionListener(this::EventDateFieldActionPerformed);

        ScheduleEventButton.setBackground(new java.awt.Color(255, 51, 0));
        ScheduleEventButton.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        ScheduleEventButton.setForeground(new java.awt.Color(255, 255, 255));
        ScheduleEventButton.setText("Schedule Event");
        ScheduleEventButton.addActionListener(this::ScheduleEventButtonActionPerformed);

        organizerTitle.setBackground(new java.awt.Color(0, 0, 0));
        organizerTitle.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 12)); // NOI18N
        organizerTitle.setForeground(new java.awt.Color(255, 255, 255));
        organizerTitle.setText("Select Organizer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EventCodeTitle)
                    .addComponent(EventNameTitle)
                    .addComponent(EventDateTitle)
                    .addComponent(StartHourTitle)
                    .addComponent(EndingHourTitle)
                    .addComponent(MaxParticipantsTitle))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EndingHourField, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(StartingHourField)
                    .addComponent(EventDateField)
                    .addComponent(EventNameField)
                    .addComponent(EventCodeField)
                    .addComponent(MaxParticipantsSpinner))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SelectRoomTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SelectRoomCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(organizerTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(organizerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ScheduleEventButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EventCodeTitle)
                    .addComponent(EventCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectRoomTitle)
                    .addComponent(SelectRoomCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EventNameTitle)
                    .addComponent(EventNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EventDateTitle)
                    .addComponent(EventDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(organizerTitle)
                    .addComponent(organizerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartHourTitle)
                    .addComponent(StartingHourField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EndingHourTitle)
                    .addComponent(EndingHourField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaxParticipantsTitle)
                    .addComponent(MaxParticipantsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScheduleEventButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ScheduleEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScheduleEventButtonActionPerformed
if (OrganizerFrame.organizersList.isEmpty() || RoomFrame.roomsList.isEmpty()) return;
        
String code = EventCodeField.getText();
String title = EventNameField.getText();
String eventDate = EventDateField.getText();
int startingHour = Integer.parseInt(StartingHourField.getText());
int endingHour = Integer.parseInt(EndingHourField.getText());

int maxParticipants = (int) MaxParticipantsSpinner.getValue();
Room room = RoomFrame.roomsList.get(SelectRoomCombo.getSelectedIndex());
Organizer organizer = OrganizerFrame.organizersList.get(organizerCombo.getSelectedIndex());


DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
LocalDate parsedEventDate = LocalDate.parse(eventDate,formatter);




if(parsedEventDate.isBefore(LocalDate.now())) {
    System.out.println("Outdated date :)");
     JOptionPane.showMessageDialog(this, "You can't make an event before today :)", "Date Error", JOptionPane.ERROR_MESSAGE);
     return;
}


if (code.isBlank() || title.isBlank() || eventDate.isBlank() || StartingHourField.getText().isBlank() || !(StartingHourField.getText().matches("\\d+")) ||  !(EndingHourField.getText().matches("\\d+")) ||  EndingHourField.getText().isBlank() || startingHour < 0 || endingHour < 0 || startingHour >= endingHour || startingHour > 22 || endingHour > 23 ||  maxParticipants < 0){
    System.out.println("Invalid Information !");
      JOptionPane.showMessageDialog(this, "Make sure to fill all columns correctly", "Invalid Information", JOptionPane.ERROR_MESSAGE);
   return;
}



if (maxParticipants > room.capacity){
    System.out.println("Room capacity is not suficient for this event");
      JOptionPane.showMessageDialog(this, "This room's capacity is not enough for your event", "Room Capacity Error", JOptionPane.ERROR_MESSAGE);
      return;
}



for (Event event : EventFrame.eventsList){
    if (event.code.equals(code)){
        System.out.println("event already organized");
         JOptionPane.showMessageDialog(this, "an event with the same code already exists", "Redundant event code", JOptionPane.ERROR_MESSAGE);
         return;
    }
 if (event.room.roomNumber.equals(room.roomNumber) && event.hasConflict(new Event(code,title,eventDate,startingHour,endingHour,maxParticipants))) {
     System.out.println("This event can't be hosted in the same room since another event is taking place there");
         JOptionPane.showMessageDialog(this, "Another event is hosted in this room at the same time ", "Events Conflict in room", JOptionPane.ERROR_MESSAGE);
         return;
 }
}
    


Event event = new Event(code,title,eventDate,startingHour,endingHour,maxParticipants);
event.assignRoom(room);
organizer.addEvent(event);
EventFrame.eventsList.add(event);
EventFrame.loadEventsToTable();
this.dispose();

    }//GEN-LAST:event_ScheduleEventButtonActionPerformed

    private void EventDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EventDateFieldActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EndingHourField;
    private javax.swing.JLabel EndingHourTitle;
    private javax.swing.JTextField EventCodeField;
    private javax.swing.JLabel EventCodeTitle;
    private javax.swing.JFormattedTextField EventDateField;
    private javax.swing.JLabel EventDateTitle;
    private javax.swing.JTextField EventNameField;
    private javax.swing.JLabel EventNameTitle;
    private javax.swing.JSpinner MaxParticipantsSpinner;
    private javax.swing.JLabel MaxParticipantsTitle;
    private javax.swing.JButton ScheduleEventButton;
    private javax.swing.JComboBox<String> SelectRoomCombo;
    private javax.swing.JLabel SelectRoomTitle;
    private javax.swing.JLabel StartHourTitle;
    private javax.swing.JTextField StartingHourField;
    private javax.swing.JComboBox<String> organizerCombo;
    private javax.swing.JLabel organizerTitle;
    // End of variables declaration//GEN-END:variables
}
