/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SubFrames;

import javax.swing.JOptionPane;
import ApplicationGui.EquipmentFrame;
import Classes.Equipment;
import java.awt.Color;

/**
 *
 * @author Dell 2024
 */
public class AddEquipmentFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddEquipmentFrame.class.getName());

    /**
     * Creates new form AddEquipmentFrame
     */
    public AddEquipmentFrame() {
        initComponents();
         this.setDefaultCloseOperation(AddEquipmentFrame.DISPOSE_ON_CLOSE);
          this.getContentPane().setBackground(new Color(18, 17, 17));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameTitle = new javax.swing.JLabel();
        QuantAvailableTitle = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        AddEquipmentButton = new javax.swing.JButton();
        quantitySpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NameTitle.setBackground(new java.awt.Color(0, 0, 0));
        NameTitle.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        NameTitle.setForeground(new java.awt.Color(255, 255, 255));
        NameTitle.setText("Name");

        QuantAvailableTitle.setBackground(new java.awt.Color(0, 0, 0));
        QuantAvailableTitle.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        QuantAvailableTitle.setForeground(new java.awt.Color(255, 255, 255));
        QuantAvailableTitle.setText("Quantity Available");

        NameTextField.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 12)); // NOI18N
        NameTextField.addActionListener(this::NameTextFieldActionPerformed);

        AddEquipmentButton.setBackground(new java.awt.Color(0, 0, 0));
        AddEquipmentButton.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 12)); // NOI18N
        AddEquipmentButton.setForeground(new java.awt.Color(255, 255, 255));
        AddEquipmentButton.setText("Add Equipment");
        AddEquipmentButton.addActionListener(this::AddEquipmentButtonActionPerformed);

        quantitySpinner.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AddEquipmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(QuantAvailableTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(NameTitle)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(quantitySpinner))
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameTitle))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantAvailableTitle)
                    .addComponent(quantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddEquipmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldActionPerformed

    private void AddEquipmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEquipmentButtonActionPerformed
    String name = NameTextField.getText();
    int quantityAvailable = (int) quantitySpinner.getValue();
    
    if (name.isBlank() || quantityAvailable <= 0 || name.matches(".*\\d.*")) {
        System.out.println("Invalid Equipment Information !");
        JOptionPane.showMessageDialog(this, "Invalid Equipment Information !", "Equipement Info Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    int id = EquipmentFrame.equipmentsList.size() + 1;
    Equipment eq = new Equipment(id,name,quantityAvailable);
    EquipmentFrame.equipmentsList.add(eq);
    EquipmentFrame.loadEquipmentToList();
        System.out.println("Equipment added successfully");
        this.dispose();
    
    
    

        
    }//GEN-LAST:event_AddEquipmentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEquipmentButton;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel NameTitle;
    private javax.swing.JLabel QuantAvailableTitle;
    private javax.swing.JSpinner quantitySpinner;
    // End of variables declaration//GEN-END:variables
}
