/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SubFrames;
import ApplicationGui.OrganizerFrame;
import javax.swing.JOptionPane;
import Classes.Organizer;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Dell 2024
 */
public class AddOrganizerFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddOrganizerFrame.class.getName());

    /**
     * Creates new form AddOrganizerFrame
     */
    public AddOrganizerFrame() {
        initComponents();
        this.setDefaultCloseOperation(AddOrganizerFrame.DISPOSE_ON_CLOSE);
         this.getContentPane().setBackground(new Color(18, 17, 17));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameTitle = new javax.swing.JLabel();
        EmailTitle = new javax.swing.JLabel();
        ClubNameTitle = new javax.swing.JLabel();
        AddOrganizerButton = new javax.swing.JButton();
        NameTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        ClubNameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NameTitle.setBackground(new java.awt.Color(0, 0, 0));
        NameTitle.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 12)); // NOI18N
        NameTitle.setForeground(new java.awt.Color(255, 255, 255));
        NameTitle.setText("Name");

        EmailTitle.setBackground(new java.awt.Color(0, 0, 0));
        EmailTitle.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 12)); // NOI18N
        EmailTitle.setForeground(new java.awt.Color(255, 255, 255));
        EmailTitle.setText("Email");

        ClubNameTitle.setBackground(new java.awt.Color(0, 0, 0));
        ClubNameTitle.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 12)); // NOI18N
        ClubNameTitle.setForeground(new java.awt.Color(255, 255, 255));
        ClubNameTitle.setText("Club Name");

        AddOrganizerButton.setBackground(new java.awt.Color(0, 0, 0));
        AddOrganizerButton.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        AddOrganizerButton.setForeground(new java.awt.Color(255, 255, 255));
        AddOrganizerButton.setText("Add Organizer");
        AddOrganizerButton.addActionListener(this::AddOrganizerButtonActionPerformed);

        ClubNameTextField.addActionListener(this::ClubNameTextFieldActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ClubNameTitle)
                    .addComponent(EmailTitle)
                    .addComponent(NameTitle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NameTextField)
                    .addComponent(EmailTextField)
                    .addComponent(ClubNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(AddOrganizerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameTitle)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailTitle)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClubNameTitle)
                    .addComponent(ClubNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(AddOrganizerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClubNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClubNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClubNameTextFieldActionPerformed

    private void AddOrganizerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddOrganizerButtonActionPerformed
     String name = NameTextField.getText();
     String email = EmailTextField.getText();
     String clubName = ClubNameTextField.getText();
     
     Pattern regex = Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);
     Matcher matcher = regex.matcher(email);
   
     if (name.isBlank() || email.isBlank() || clubName.isBlank() || name.matches(".*\\d.*") || !(matcher.matches())){
         System.out.println("Incomplete or Incorrect Information !");
        JOptionPane.showMessageDialog(this, "Fill all Information correctly", "Information Incorrect/Incomplete !", JOptionPane.ERROR_MESSAGE);
         return;
     }
       int id  = OrganizerFrame.organizersList.size() + 1 ;
       Organizer org = new Organizer(id,name,email,clubName);
       
       OrganizerFrame.organizersList.add(org);
       OrganizerFrame.loadOrganizersToTable();
        System.out.println("Organizer Added Successfully");
        
        this.dispose();
       
     
     
    }//GEN-LAST:event_AddOrganizerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddOrganizerButton;
    private javax.swing.JTextField ClubNameTextField;
    private javax.swing.JLabel ClubNameTitle;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel EmailTitle;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel NameTitle;
    // End of variables declaration//GEN-END:variables
}
