/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SubFrames;

import javax.swing.JOptionPane;
import ApplicationGui.RoomFrame;
import Classes.Room;
import java.awt.Color;

/**
 *
 * @author Dell 2024
 */
public class AddRoomFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddRoomFrame.class.getName());

    /**
     * Creates new form AddRoomFrame
     */
    public AddRoomFrame() {
        initComponents();
        this.setDefaultCloseOperation(AddRoomFrame.DISPOSE_ON_CLOSE);
         this.getContentPane().setBackground(new Color(18, 17, 17));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buildingTitle = new javax.swing.JLabel();
        capacityTitle = new javax.swing.JLabel();
        addRoomButton = new javax.swing.JButton();
        buildingTextField = new javax.swing.JTextField();
        capacitySpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buildingTitle.setBackground(new java.awt.Color(0, 0, 0));
        buildingTitle.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        buildingTitle.setForeground(new java.awt.Color(255, 255, 255));
        buildingTitle.setText("Building");

        capacityTitle.setBackground(new java.awt.Color(0, 0, 0));
        capacityTitle.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        capacityTitle.setForeground(new java.awt.Color(255, 255, 255));
        capacityTitle.setText("Capacity");

        addRoomButton.setBackground(new java.awt.Color(0, 0, 0));
        addRoomButton.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        addRoomButton.setForeground(new java.awt.Color(255, 255, 255));
        addRoomButton.setText("Add Room");
        addRoomButton.addActionListener(this::addRoomButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(capacityTitle)
                            .addComponent(buildingTitle))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(capacitySpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(buildingTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(addRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buildingTitle)
                    .addComponent(buildingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capacityTitle)
                    .addComponent(capacitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(addRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomButtonActionPerformed
        String building = buildingTextField.getText();
        int capacity = (int) capacitySpinner.getValue();
        
        if (capacity < 0 || building.isBlank()){
        System.out.println("Invalid Information !");
         JOptionPane.showMessageDialog(this, "Make sure the Information is Right", "Invalid Information !", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        String roomNumber =Integer.toString( RoomFrame.roomsList.size()+1);
        Room room = new Room(roomNumber,building,capacity);
        RoomFrame.roomsList.add(room);
        RoomFrame.loadRoomsToTable();
        System.out.println("Room added successfully !");
        this.dispose();
    }//GEN-LAST:event_addRoomButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRoomButton;
    private javax.swing.JTextField buildingTextField;
    private javax.swing.JLabel buildingTitle;
    private javax.swing.JSpinner capacitySpinner;
    private javax.swing.JLabel capacityTitle;
    // End of variables declaration//GEN-END:variables
}
