/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SubFrames;
import ApplicationGui.StudentFrame;
import javax.swing.JOptionPane;
import Classes.Student;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;


/**
 *
 * @author Dell 2024
 */
public class AddStudentFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddStudentFrame.class.getName());

    /**
     * Creates new form AddStudentFrame
     */
    public AddStudentFrame() {
        initComponents();
        this.setDefaultCloseOperation(AddStudentFrame.DISPOSE_ON_CLOSE);
         this.getContentPane().setBackground(new Color(18, 17, 17));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameTitle = new javax.swing.JLabel();
        EmailTitle = new javax.swing.JLabel();
        LevelTitle = new javax.swing.JLabel();
        DepartmentTitle = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        LevelTextField = new javax.swing.JTextField();
        DepartmentTextField = new javax.swing.JTextField();
        AddStudentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NameTitle.setBackground(new java.awt.Color(0, 0, 0));
        NameTitle.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        NameTitle.setForeground(new java.awt.Color(255, 255, 255));
        NameTitle.setText("Name");

        EmailTitle.setBackground(new java.awt.Color(0, 0, 0));
        EmailTitle.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        EmailTitle.setForeground(new java.awt.Color(255, 255, 255));
        EmailTitle.setText("Email");

        LevelTitle.setBackground(new java.awt.Color(0, 0, 0));
        LevelTitle.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        LevelTitle.setForeground(new java.awt.Color(255, 255, 255));
        LevelTitle.setText("Level");

        DepartmentTitle.setBackground(new java.awt.Color(0, 0, 0));
        DepartmentTitle.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        DepartmentTitle.setForeground(new java.awt.Color(255, 255, 255));
        DepartmentTitle.setText("Department");

        LevelTextField.addActionListener(this::LevelTextFieldActionPerformed);

        AddStudentButton.setBackground(new java.awt.Color(0, 0, 0));
        AddStudentButton.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        AddStudentButton.setForeground(new java.awt.Color(255, 255, 255));
        AddStudentButton.setText("Add Stduent");
        AddStudentButton.addActionListener(this::AddStudentButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DepartmentTitle)
                    .addComponent(LevelTitle)
                    .addComponent(EmailTitle)
                    .addComponent(NameTitle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NameTextField)
                    .addComponent(EmailTextField)
                    .addComponent(LevelTextField)
                    .addComponent(DepartmentTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameTitle)
                            .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(EmailTitle))
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LevelTitle)
                    .addComponent(LevelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepartmentTitle)
                    .addComponent(DepartmentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LevelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LevelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LevelTextFieldActionPerformed

    private void AddStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentButtonActionPerformed
       String name = NameTextField.getText();
       String email = EmailTextField.getText();
       String level = LevelTextField.getText();
       String department = DepartmentTextField.getText();
       
       
     Pattern regex = Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);
     Matcher matcher = regex.matcher(email);
       
       if(name.isBlank() || name.matches(".*\\d.*") || email.isBlank() || level.isBlank() ||  department.matches(".*\\d.*") || department.isBlank() || !(matcher.matches())){
           System.out.println("Information Incomplete/incorrect !");
            JOptionPane.showMessageDialog(this, "Fill all Information correctly", "Information Incomplete/incorrect !", JOptionPane.ERROR_MESSAGE);
            return;
       }
       int id = StudentFrame.studentsList.size() + 1 ;
       
       Student std = new Student(id,name,email,level,department);
       StudentFrame.studentsList.add(std);
       StudentFrame.loadStudentsToTable();
        System.out.println("Student added successfully");
        this.dispose();
       
    }//GEN-LAST:event_AddStudentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddStudentButton;
    private javax.swing.JTextField DepartmentTextField;
    private javax.swing.JLabel DepartmentTitle;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel EmailTitle;
    private javax.swing.JTextField LevelTextField;
    private javax.swing.JLabel LevelTitle;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel NameTitle;
    // End of variables declaration//GEN-END:variables
}
